require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.colorscheme"
spec "user.devicons"

spec "user.treesitter"
spec "user.mason"
spec "user.whichkey"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.harpoon"
spec "user.none-ls"
spec "user.gitsigns"
spec "user.nvimtree"
spec "user.lualine"
spec "user.autopairs"
spec "user.neogit"
spec "user.project"


require "user.lazy"
